version: "3.9"
services:
  discordbot:
    build: .
    container_name: discordbot
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_USERNAME=
      - REDIS_PASSWORD=
      - REDIS_DB_ID=0

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"