version: "3.9"
services:
  discordbot:
    build: .
    container_name: discordbot
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_USERNAME=
      - REDIS_PASSWORD=
      - REDIS_DB_ID=0
      - LOGS_PATH=./logs/
      - TOOLS_PATH=./tools/
    networks:
      - internal
      - external

  redis:
    image: redis:7-alpine
    container_name: redis
    networks:
      - internal

networks:
  internal:
    driver: bridge
    internal: true
  external:
    driver: bridge